### ISSUE TITLE
这个错误如何解决

### ISSUE THREAD

**Issue by cainiaohaonan** [AnswerAIL/fabric-sdk-server#3]
![image](https://user-images.githubusercontent.com/44564666/58396526-a4776200-807f-11e9-99f9-e8fcfa6fcdaf.png)

**Comment by AnswerAIL** [comment]
这个是因为环境没有清除干净导致的问题。 包括挂载盘目录和智能合约镜像都需要清理掉

**Comment by cainiaohaonan** [comment]
> 这个是因为环境没有清除干净导致的问题。包括挂载盘目录和智能合约镜像都需要清理掉
清楚命令哪里可以找到。

**Comment by AnswerAIL** [comment]
a
