### ISSUE TITLE
创建新通道的时候报错。

### ISSUE THREAD

**Issue by cainiaohaonan** [AnswerAIL/fabric-sdk-server#8]
![image](https://user-images.githubusercontent.com/44564666/59751265-cd6fc900-92b2-11e9-9e57-2179ce76e7b1.png)
![image](https://user-images.githubusercontent.com/44564666/59751301-dd87a880-92b2-11e9-854e-fad1566ec37d.png)
还有如何创建两个Orderer的集群环境？按照网上几个教程都没有成功。。。。

**Comment by AnswerAIL** [comment]
修改channelName="mychannel"
